---
title: "hospital-admissions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Add packages to library}

library(tidyverse)
library(here)

```

```{r Load Data}

data_dictionary<- read.delim("~/Maestria/Open and reproducible data science/R and GitHub Practice/hospital-admissions/Inputs/pop_demo_data_dictionary.csv")

demographics<- read.csv("~/Maestria/Open and reproducible data science/R and GitHub Practice/hospital-admissions/Inputs/population_demographics.csv")

```

```{r Read Data}

head(demographics)
head(data_dictionary)
glimpse(demographics)
unique(demographics$deprivation)
unique(demographics$age)

demographics_noNA<- demographics %>% 
  drop_na() %>%
  filter(deprivation !="NA")
glimpse(demographics_noNA)
unique(demographics_noNA)
```


```{r Describe median, minimum and maximum}


summarize(demographics_noNA, median(age), min(age), max(age))

 
demographics_noNA %>% 
 summarise_at(vars(deprivation),
               list(min=min, max=max,mean=mean, sd=sd, Q1=~quantile(deprivation, probs=0.25), 
                    median=median, Q3=~quantile(deprivation, probs=0.75)))
```

#Questions


Are there any problems with the values of age and deprivation?

Age: extreme values that go from 0 to 150, last one certainly a mistake, the first one would need corroboration


What is the minimum, maximum and median age for each deprivation level?


```{r Describe median, minimum and maximum for deprivation level}

demographics_noNA %>% 
 group_by(deprivation) %>% 
 summarise_at(vars(age),
               list(min=min, max=max,mean=mean, sd=sd, Q1=~quantile(age, probs=0.25), 
                    median=median, Q3=~quantile(age, probs=0.75)))
```

